#!/bin/bash

declare -r myname="info1"

notebook() {
    echo "starting notebook..."
    jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 ${NOTEBOOK_DIR}
}

build() {
    echo "starting build..."
    echo "arguments: $@"
}

help() {
	cat <<-EOF
	This script starts a jupyter notebook or runs a build task

	Usage: ${myname} {notebook|build}
	    notebook              Start the jupyter notebook
	    build                 Runs a build task

	EOF
}

case "${1:-}" in
	notebook)
	notebook
	;;

	build)
	build "${@:2}"
	;;

	-h|--help)
	help
	exit 0
	;;

	*)
	help
	exit 1
	;;
esac

exit 0